### ISSUE TITLE
connection.adapter_name for Postgresql

### ISSUE THREAD

**Issue by mflorisson** [geokit/geokit-rails#10]
There may be a bogg in Geokit::ActsAsMappable::SingletonMethods in adapter method:

klass = Adapters.const_get(connection.adapter_name.camelcase)
should be (I think)
klass = Adapters.const_get(connection.adapter_name)

Otherwise I receive an exception: uninitialized constant Geokit::Adapters::Postgresql

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues. If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
