### ISSUE TITLE
Please check Rails 5.0 compatibility

### ISSUE THREAD

**Issue by wfried** [geokit/geokit-rails#103]
Rails 5 was recently completed and released.  When I upgrade my project to Rails 5, Bundler flags a compatibility issue with geokit-rails.  Could you please add tests for Rails 5.0 and look at any compatibility issues?

**Comment by wfried** [comment]
Just checking in - is this gem still being maintained?  It doesn't look like any issues have been responded to this year.

**Comment by mnoack** [comment]
@wfried I respond quite quickly to Pull Requests, but I tend not to actively work on issues.

**Comment by mnoack** [comment]
@wfried In the last day I've merged lots of PR's made a few more fixes and released 2.2.0 from the latest master. Give that a go and see how it goes.
