### ISSUE TITLE
Using :joins creates multiple INNER JOIN statements - error

### ISSUE THREAD

**Issue by xpepermint** [geokit/geokit-rails#11]
Example:
@markers = Marker.find_within(@distance, 
:origin => @origin,
:include => [:tags],
:joins => [:user, :point],
:conditions => ['markers.xy=? AND tags.tag=?', 'xxx', 'yyy'],
:order => 'distance')

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues. If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
