### ISSUE TITLE
Is there a list of geocoding providers that this gem works with currently? I can't use google anymore due to TOS.

### ISSUE THREAD

**Issue by dlp21103** [geokit/geokit-rails#111]

**Comment by mnoack** [comment]
@dlp21103 The list is in the README for the geokit gem (a dependency of this gem):
https://github.com/geokit/geokit/

**Comment by dlp21103** [comment]
I saw that list but was just making sure it was current since Yahoo BOSS was discontinued last year and the geocoder.us site hasn't been working for months. I'll try the rest. Thanks.
