### ISSUE TITLE
Using 'within' without creating a geocode request

### ISSUE THREAD

**Issue by ericinthewild** [geokit/geokit-rails#131]
Hello! Fantastic gem, this is providing me with some critical functionality for my app.

I am now trying to reduce the amount of geocode API calls during code execution. I am saving the geocoded lat / long upon creating a new 'job' and entering its address.

Later in my app I am needing to find vendors for that job within 100 miles, so I am using the code below and it is working as expected, however I still see a geocoder API request being made when executing this code. Is there a way to use the within method without the need to make another request to the geocoder, as we already have our predefined lat / longs?

```
      @PUGeo = Geokit::GeoLoc.new
      @PUGeo.lat = @workorder.job.PULatitude
      @PUGeo.lng = @workorder.job.PULongitude
      @vendors = Vendor.within(100, :origin => @PUGeo)
```

**Comment by mnoack** [comment]
Sorry @ericinthewild - I think you make a smart point. If you have a look around at the code as it flows (I love to use pry or byebug) you might be able to find it, and make a change to geokit so it only calls it if needed.

I would gladly accept such a Pull Request to geokit.

But unfortunately I'm more what you call a "passive maintainer" (I maintain the project by accepting improvements from the community, but I don't use geokit much anymore personally, nor have a personal need to make these improvements for myself)

Geokit isn't a very complex project so by all means get in the code and have a look around.
