### ISSUE TITLE
Records have invalid ids when using all(:within => distance, :origin => location) on a has_many :through association

### ISSUE THREAD

**Issue by myronmarston** [geokit/geokit-rails#14]
The problem is that geokit-rails sets the find's :select option to "*", and the has_many :through association uses a join...causing it to include multiple id columns.  I've got a fix here:

http://github.com/myronmarston/geokit-rails/commit/a1caf6dcde7406988798685de73b2b87370539c5

It'd be nice to get my fix pulled into the official repo.  How do you like to receive patches?  I sent a pull request a while ago and never got a response.

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues.

The updates that made the gem work with Rails 3 may have solved this.

If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
