### ISSUE TITLE
before_validation_on_create removed in Rails 3

### ISSUE THREAD

**Issue by bobbymarko** [geokit/geokit-rails#16]
Rails 3 is giving me a "no method found" error when I enable auto_geocode.
The validation should be called like so:
`before_validation :auto_geocode_address, :on => :create`
because `before_validation_on_create` has been deprecated.
Although when I change the callback to that code WEBrick crashes so there's more to the bug.

Running Rails 3 Beta 2 with ruby 1.9.2

**Comment by ryankopf** [comment]
This change appears to have been implemented. Closing as fixed.
