### ISSUE TITLE
Rails3 syntax

### ISSUE THREAD

**Issue by craibuc** [geokit/geokit-rails#19]
I'm trying to migrate to Rails3 syntax.  The following query works:

```
@users = User.find(
  :all,
  :joins => "INNER JOIN profiles AS profiles ON users.id=profiles.user_id",
  :conditions => ["users.disabled = ? AND users.hidden = ?", false, false],
  :include => :profile,
  :origin => ll,
  :units => :miles, 
  :order => order_by
  ).paginate(:per_page => @per_page, :page => params[:page])
```

If I convert this query to Rails3 syntax using scopes, the query resembles:
@users = User.valid.joins(:profile).includes(:profile).order(order_by).paginate(:per_page => @per_page, :page => params[:page])

Question: how do I reference the :units and :origin in this syntax?  I've tried a variation of the Rails3 syntax to use scopes and the .find method:

```
@users = User.valid.joins(:profile).includes(:profile).find(
  :all,
  :origin => ll,
  :units => :miles, 
  :order => order_by
  ).paginate(:per_page => @per_page, :page => params[:page])
```

but I get an error that reads "Unknown key(s): origin, units".

Is the plugin Rails3 compatible?

**Comment by ryankopf** [comment]
Closing this as there have been significant updates since.
