### ISSUE TITLE
session[:geo_location] returns nil

### ISSUE THREAD

**Issue by blanchma** [geokit/geokit-rails#32]
I added in the top of the controller:

geocode_ip_address

And then:

logger.info "======= GEOLOCATION ==========="
    logger.info session[:geo_location]

It returns: nil in the logs

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues. If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
