### ISSUE TITLE
Find Query 

### ISSUE THREAD

**Issue by definelabs** [geokit/geokit-rails#33]
Is it possible to find Location within a country.

For example if I give input as 36.03,-115.23(this reverse gecodes to Las Vegas , US) 

is it possible to find Locations within United States or for that matter within Las Vegas

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues. If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
