### ISSUE TITLE
Missing 'distance' field on returned instances

### ISSUE THREAD

**Issue by xnzacc** [geokit/geokit-rails#39]
As documented:

The plug-in creates a calculated distance field on AR instances that have been retrieved throw a Geokit location query. By default, these fields are known as "distance" but this can be changed through the :distance_field_name key.

"distance" field on returned objects is not available.

**Comment by speakingcode** [comment]
Is there no way to get the actual distance? I don't want to sort by distance i want to display the distance to my user, I need the actual field... how to get the distance field?

**Comment by ccoeder** [comment]
@speakingcode did you figured it out? i need help 😞

**Comment by ccoeder** [comment]
You can look at this issue, there is patch on that https://github.com/geokit/geokit-rails/issues/56
