### ISSUE TITLE
"geocode" method failing for authenticated geocoder.us call

### ISSUE THREAD

**Issue by cj2** [geokit/geokit-rails#4]
When using authenticated requests to geocoder.us the requests fail with 401 not authorized. Replacing line 166 of geocoders.rb with the code below solves the problem.

res = Net::HTTP.start(uri.host, uri.port) {|http|
  http.request(req)
}

Is this mis-configuration or a problem with the proxy code?

**Comment by ryankopf** [comment]
I am closing all issues that are more than 6 years old now, as the gem has had significant updates and is likely people with these old issues are no longer having the issues. If you are currently still experiencing this issue or need help feel free to submit a new issue, thank you.
