### ISSUE TITLE
Where is config file?

### ISSUE THREAD

**Issue by tjoneseng** [geokit/geokit-rails#51]
The README refers to file assets/api_keys_template for a default configuration file.  This seems to be missing.  I see no source for the configuration file anywhere in the source.  I was expecting a rake task or some such to generate the default configuration file.

**Comment by kwerle** [comment]
It would be much much better to have the 'nearly useless' config file in place with all the options listed and appropriately commented out - just like virtually every other gem does.
Way better to see what's possible and have it be clear.
