### ISSUE TITLE
How to handle multiple lat, lng feilds in a single model ?

### ISSUE THREAD

**Issue by vishalvijay** [geokit/geokit-rails#78]
Hi
Consider a model `User` with attributes `last_lat`, `last_lng`, `current_lat` and `current_lng`. How do I manage to add `acts_as_mappable` for both points.

**Comment by rafaeljcadena** [comment]
Same here. Any ideas?

**Comment by ryankopf** [comment]
You currently cannot and this is not likely to be supported anytime soon.

You can achieve the same effect by creating a new model Location that belongs to the user. A user could then have both a current and a previous location object, and you would search by searching the Location objects which can be mappable. 

If that's too much change for your code, you could create just a past location model that is only used for former locations.
