### ISSUE TITLE
rake test failure

### ISSUE THREAD

**Issue by mflorisson** [geokit/geokit-rails#9]
I'm trying to execute test, but it's failing with this message: 
uninitialized constant MockPerson::MockFamily

DB=postgresql rake test
Here is an extract of backtrace

/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:105:in `const_missing': uninitialized constant MockPerson::MockFamily (NameError)
    from /var/lib/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:2199:in`compute_type'
    from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
    from /var/lib/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:2195:in`compute_type'
    from /var/lib/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:156:in `send'
    from /var/lib/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:156:in`klass'
    from ./lib/geokit-rails/acts_as_mappable.rb:122:in `end_of_reflection_chain'
    from ./lib/geokit-rails/acts_as_mappable.rb:64:in`acts_as_mappable'
    from ./test/../test/models/mock_person.rb:3
...

**Comment by ryankopf** [comment]
I don't think this is an issue related to the gem and so I am closing this.
