### ISSUE TITLE
Could not find generator 'geokit_rails:install'

### ISSUE THREAD

**Issue by thehashrocket** [geokit/geokit-rails#95]
I added the gem, ran `bundle install`, and then went to do the important post install instructions. However, upon doing that I received this error:

```
rails g geokit_rails:install
Could not find generator 'geokit_rails:install'. Maybe you meant 'responders:install', 'devise:install' or 'devise_invitable:install'
Run `rails generate --help` for more options.
```

Am I missing something? I am using the following:

```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
Rails 4.2.4
```

**Comment by rylanb** [comment]
@thehashrocket Which version of geokit rails do you have? 

gem 'geokit-rails', github: 'geokit/geokit-rails' should solve that issue for you, I believe. The documentatino is out of date.

**Comment by jponc** [comment]
Thanks @rylanb
